main: main.o add.o div.o print_val.o
	g++ main.o add.o div.o print_val.o -o main

main.o: main.cpp
	g++ -c main.cpp

add.o: add.cpp
	g++ -c add.cpp

div.o: div.cpp
	g++ -c div.cpp

print_val.o: print_val.cpp
	g++ -c print_val.cpp